// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

window.Fibonacci = (function() {

  function Fibonacci() {
    this.getFibAry = __bind(this.getFibAry, this);

    this.getFibStr = __bind(this.getFibStr, this);

    this.getFib = __bind(this.getFib, this);

  }

  Fibonacci.prototype.fibAry = [0, 1];

  Fibonacci.prototype.getFib = function(n) {
    var ret;
    if (this.fibAry[n] != null) {
      return this.fibAry[n];
    }
    ret = (this.getFib(n - 1)) + (this.getFib(n - 2));
    this.fibAry[n] = ret;
    return ret;
  };

  Fibonacci.prototype.getFibStr = function(n, separator) {
    var ary;
    if (separator == null) {
      separator = ",";
    }
    this.getFib(n);
    ary = this.fibAry.slice(0, n + 1);
    return ary.join(separator);
  };

  Fibonacci.prototype.getFibAry = function(n) {
    var ary;
    this.getFib(n);
    ary = this.fibAry.slice(0, n + 1);
    return ary;
  };

  return Fibonacci;

})();
